name: CompVer

on:
  push:
    tags:
      - "v*.*.*"

env:
  USER_NAME: "GitHub Action"
  USER_EMAIL: "actions@github.com"
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
  COMMIT_MESSAGE: "ci: The data of the master branch was merged automatically."

jobs:
  version:
    runs-on: ubuntu-latest
    steps:

      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get the major version
        id: compver
        env:
          GITHUB_TOKEN: ${{ github.token }}
        uses: gowizzard/compver@v5.2.0
        with:
          args: "-core -block major -version1 ${{ github.ref_name }} -trim -prefix v"

      - name: Set git config
        run: |
          git config --local user.name "$USER_NAME"
          git config --local user.email "$USER_EMAIL"

      - name: Merge data from default branch
        run: |
          git fetch
          git checkout v${{ steps.compver.outputs.core_result }}
          git pull
          git merge --no-ff "origin/$DEFAULT_BRANCH" -m "$COMMIT_MESSAGE"
          git push