name: Docker Test

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

env:
    IMAGE_NAME: ${{ github.repository }}
    IMAGE_TAG: "test"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:

            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Build the Docker image
              run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .